### ISSUE TITLE
I would like the API document to be visible on the browser.

### ISSUE THREAD

**Issue by rt33** [recruit-tech/agreed#10]
I would like the API document to be visible on the browser.
like a `SWAGGER UI`
Will Agreed planning to make `Agreed-ui`?

**Comment by yosuke-furukawa** [comment]
> Will Agreed planning to make Agreed-ui?

Hi @rt33 !!

Thank you for your open issue. Currently I have a plan to create agreed visible API docs like Swagger UI, but I don't have a detail schedule. If you have an interested in agreed, we are welcome to your contribution.

**Comment by yosuke-furukawa** [comment]
close #14
