### ISSUE TITLE
[Bug?] The match with the definition of the passed query character cannot be confirmed.

### ISSUE THREAD

**Issue by yukihirop** [recruit-tech/agreed#273]
## Summary

Thank you for making a nice library,

It was discovered while trying out the [sample code](https://github.com/recruit-tech/agreed#usage).

I think there is a problem with the code here.

https://github.com/recruit-tech/agreed/blob/d8577704259ddec4a32cabb993ba671e6c6c1a84/packages/core/lib/check/checker.js#L42

### actual

```bash
$ curl http://localhost:3010/user/yosuke\?q\=foo
{"message":"hello yosuke foo","images":["http://example.com/foo.jpg","http://example.com/bar.jpg"],"themes":{"name":"green"}}%

$ curl http://localhost:3010/user/yosuke\?q\=fooaaaaa
{"message":"hello yosuke fooaaaaa","images":["http://example.com/foo.jpg","http://example.com/bar.jpg"],"themes":{"name":"green"}}%

$ curl http://localhost:3010/user/yosuke\?q\=fooaaaaaaaaaaaa
{"message":"hello yosuke fooaaaaaaaaaaaa","images":["http://example.com/foo.jpg","http://example.com/bar.jpg"],"themes":{"name":"green"}}%
```

### expected

```bash
$ curl http://localhost:3010/user/yosuke\?q\=foo
{"message":"hello yosuke foo","images":["http://example.com/foo.jpg","http://example.com/bar.jpg"],"themes":{"name":"green"}}%

$ curl http://localhost:3010/user/yosuke\?q\=fooaaaaa
Agree Not Found

$ curl http://localhost:3010/user/yosuke\?q\=fooaaaaaaaaaaaa
Agree Not Found
```

Shouldn't the URL be matched against the values ​​in `values.someQueryStrings` ?

```js
// save as agreed.js
module.exports = [
  {
    request: {
      path: '/user/:id',
      method: 'GET',
      query: {
        q: '{:someQueryStrings}',
      },
      values: {
        id: 'yosuke',
        someQueryStrings: 'foo'
      },
```

## Environment

```
$ node -v
v13.13.0
```

```
"@agreed/cli": "^5.1.10"
```

**Comment by yosuke-furukawa** [comment]
oh, I have not caught this problem, i will try.

**Comment by yosuke-furukawa** [comment]
ah i have got it.
This is an expected behavior. agreed does not check `query.value`.
`query.value` is used for `@agreed/client` to send the request.
If you would like to create stub server, `query.value` is not required.

**Comment by yukihirop** [comment]
@yosuke-furukawa 

Thank you for your answer.

I will explain the specific problem using a simple example below.

The problem is immediately discovered when the following agreed file is read.

```js
// save as agreed.js
module.exports = [
   // define foo
  {
    request: {
      path: '/user/:id',
      method: 'GET',
      query: {
        q: '{:someQueryStrings}',
      },
      values: {
        id: 'yosuke',
        someQueryStrings: 'foo'
      },
    },
    response: {
      headers: {
        'x-csrf-token': 'csrf-token', 
      },
      body: {
        foo: 'foo',
      }
    },
  },
  // define bar
  {
    request: {
      path: '/user/:id',
      method: 'GET',
      query: {
        q: '{:someQueryStrings}',
      },
      values: {
        id: 'yosuke',
        someQueryStrings: 'bar'
      },
    },
    response: {
      headers: {
        'x-csrf-token': 'csrf-token', 
      },
      body: {
        bar: 'bar'
      },
    },
  },  
]
```

### expected

The user's expectations defined in this way should be as follows,

```bash
$ curl http://localhost:3010/user/yosuke\?q\=foo
{"foo":"foo"}%

$ curl http://localhost:3010/user/yosuke\?q\=bar
{"bar":"bar"}%

$ curl http://localhost:3010/user/yosuke\?q\=baz
Agreed Not Found
```

### actual

Actually, it doesn't collate by looking at the value of query, so what if it is only as follows.

```bash
$ curl http://localhost:3010/user/yosuke\?q\=foo
{"foo":"foo"}%

$ curl http://localhost:3010/user/yosuke\?q\=bar
{"foo":"foo"}%

$ curl http://localhost:3010/user/yosuke\?q\=baz
{"foo":"foo"}%
```

I think this is inconvenient because the definition cannot be divided due to the difference in the query string.

### problem

If the definition order is reversed.

```js
// save as agreed.js
module.exports = [
   // define bar
  {
    request: {
      path: '/user/:id',
      method: 'GET',
      query: {
        q: '{:someQueryStrings}',
      },
      values: {
        id: 'yosuke',
        someQueryStrings: 'bar'
      },
    },
    response: {
      headers: {
        'x-csrf-token': 'csrf-token', 
      },
      body: {
        bar: 'bar',
      }
    },
  },
  // define foo
  {
    request: {
      path: '/user/:id',
      method: 'GET',
      query: {
        q: '{:someQueryStrings}',
      },
      values: {
        id: 'yosuke',
        someQueryStrings: 'foo'
      },
    },
    response: {
      headers: {
        'x-csrf-token': 'csrf-token', 
      },
      body: {
        foo: 'foo'
      },
    },
  },  
]
```

The result will be like this

```bash
$ curl http://localhost:3010/user/yosuke\?q\=foo
{"bar":"bar"}%

$ curl http://localhost:3010/user/yosuke\?q\=bar
{"bar":"bar"}%

$ curl http://localhost:3010/user/yosuke\?q\=baz
{"bar":"bar"}%
```

I think it is very problematic that the response changes in the order of definition.

### Summary

Would you like to collate by looking at the value of query?

Users who want to define using query strings will use this library because they think the response is naturally separate.

I don't think this behavior should be a specification.

I love agreed which is easier to use than [json-server](https://github.com/typicode/json-server). 💘

Please consider improvement. 🙇‍♂️

**Comment by yosuke-furukawa** [comment]
This is an expected behavior. but if you need more proper behavior to match your request, it is okay to send PR. I will review your Draft PR. 

If you would like to solve this behavior as a workaround, I suggest that your agreed file will be better on that below.

```js
// save as agreed.js
module.exports = [
   // define bar
  {
    request: {
      path: '/user/:id',
      method: 'GET',
      query: {
        q: 'bar', // if you would be better to set q: 'bar' on your agreed file.
      },
      values: {
        id: 'yosuke',
        someQueryStrings: 'bar'
      },
    },
    response: {
      headers: {
        'x-csrf-token': 'csrf-token', 
      },
      body: {
        bar: 'bar',
      }
    },
  },
  // define foo
  {
    request: {
      path: '/user/:id',
      method: 'GET',
      query: {
        q: '{:someQueryStrings}',
      },
      values: {
        id: 'yosuke',
        someQueryStrings: 'foo'
      },
    },
    response: {
      headers: {
        'x-csrf-token': 'csrf-token', 
      },
      body: {
        foo: 'foo'
      },
    },
  },  
]
```

**Comment by yukihirop** [comment]
@yosuke-furukawa 

Thank you for your answer.

Thank you for your review. We will fix the test and send it in the near future...

>If you would like to solve this behavior as a workaround, I suggest that your agreed file will be better on that below.

In my case, I don't want to reuse the query string, so I'm not going to use the template string, but I think it depends on the person, so I'll support it so that it can be used.

thank you for the advice.
